"""Link mapping for cross-reference resolution across different scopes.

This module provides link mappings for different language/framework scopes
to resolve @[link_name] references to actual URLs.
"""

from collections.abc import Mapping
from typing import TypedDict


class LinkMap(TypedDict):
    """Typed mapping describing each link map entry."""

    host: str
    scope: str
    links: Mapping[str, str]


LINK_MAPS: list[LinkMap] = [
    {
        "host": "https://reference.langchain.com/python/",
        "scope": "python",
        "links": {
            # Module pages
            "langchain": "langchain",
            "langchain.agents": "langchain/agents",
            "langchain.messages": "langchain/messages",
            "langchain.tools": "langchain/tools",
            "langchain.chat_models": "langchain/models",
            "langchain.embeddings": "langchain/embeddings",
            "langchain_core": "langchain-core",
            "langchain-core": "langchain-core",
            "langchain-text-splitters": "langchain-text-splitters",
            "langchain_text_splitters": "langchain-text-splitters",
            # Agents
            "create_agent": "langchain/agents/create_agent",
            "create_agent(tools)": "langchain/agents/create_agent",
            "create_agent(response_format)": "langchain/agents/create_agent",
            "system_prompt": "langchain/agents/create_agent",
            "AgentState": "langchain/agents/AgentState",
            "ModelRequest": "langchain/agents/middleware/ModelRequest",
            "@dynamic_prompt": "langchain/agents/middleware/dynamic_prompt",
            "@before_agent": "langchain/agents/middleware/before_agent",
            "@before_model": "langchain/agents/middleware/before_model",
            "@after_model": "langchain/agents/middleware/after_model",
            "@after_agent": "langchain/agents/middleware/after_agent",
            "@wrap_tool_call": "langchain/agents/middleware/wrap_tool_call",
            "@wrap_model_call": "langchain/agents/middleware/wrap_model_call",
            # Middleware
            "AgentMiddleware": "langchain/agents/middleware/AgentMiddleware",
            "state_schema": "langchain/agents/middleware/AgentMiddleware",
            "PIIMiddleware": "langchain/agents/middleware/PIIMiddleware",
            "SummarizationMiddleware": "langchain/agents/middleware/SummarizationMiddleware",
            "HumanInTheLoopMiddleware": "langchain/agents/middleware/HumanInTheLoopMiddleware",
            "ModelCallLimitMiddleware": "langchain/agents/middleware/ModelCallLimitMiddleware",
            "ToolCallLimitMiddleware": "langchain/agents/middleware/ToolCallLimitMiddleware",
            "ModelFallbackMiddleware": "langchain/agents/middleware/ModelFallbackMiddleware",
            "TodoListMiddleware": "langchain/agents/middleware/TodoListMiddleware",
            "LLMToolSelectorMiddleware": "langchain/agents/middleware/LLMToolSelectorMiddleware",
            "ToolRetryMiddleware": "langchain/agents/middleware/ToolRetryMiddleware",
            "ModelRetryMiddleware": "langchain/agents/middleware/ModelRetryMiddleware",
            "LLMToolEmulator": "langchain/agents/middleware/LLMToolEmulator",
            "ContextEditingMiddleware": "langchain/agents/middleware/ContextEditingMiddleware",
            "ClearToolUsesEdit": "langchain/agents/middleware/ClearToolUsesEdit",
            "ContextEdit": "langchain/agents/middleware/ContextEdit",
            "InterruptOnConfig": "langchain/agents/middleware/InterruptOnConfig",
            "ShellToolMiddleware": "langchain/agents/middleware/ShellToolMiddleware",
            "FilesystemFileSearchMiddleware": "langchain/agents/middleware/FilesystemFileSearchMiddleware",
            "ClaudeBashToolMiddleware": "langchain/agents/middleware/ClaudeBashToolMiddleware",
            "StateClaudeTextEditorMiddleware": "langchain/agents/middleware/StateClaudeTextEditorMiddleware",
            "FilesystemClaudeTextEditorMiddleware": "langchain/agents/middleware/FilesystemClaudeTextEditorMiddleware",
            "StateClaudeMemoryMiddleware": "langchain/agents/middleware/StateClaudeMemoryMiddleware",
            "FilesystemClaudeMemoryMiddleware": "langchain/agents/middleware/FilesystemClaudeMemoryMiddleware",
            "StateFileSearchMiddleware": "langchain/agents/middleware/StateFileSearchMiddleware",
            "OpenAIModerationMiddleware": "langchain/agents/middleware/OpenAIModerationMiddleware",
            "ContextSize": "langchain/agents/middleware/summarization/ContextSize",
            # Messages
            "AIMessage": "langchain/messages/AIMessage",
            "AIMessage.tool_calls": "langchain/messages/AIMessage",
            "AIMessageChunk": "langchain/messages/AIMessageChunk",
            "ToolMessage": "langchain/messages/ToolMessage",
            "SystemMessage": "langchain/messages/SystemMessage",
            "HumanMessage": "langchain/messages/HumanMessage",
            "trim_messages": "langchain/messages/trim_messages",
            "UsageMetadata": "langchain/messages/UsageMetadata",
            "InputTokenDetails": "langchain/messages/InputTokenDetails",
            "MessageLikeRepresentation": "langchain/messages/MessageLikeRepresentation",
            # Content blocks
            "BaseMessage": "langchain-core/messages/BaseMessage",
            "BaseMessage(content)": "langchain-core/messages/BaseMessage",
            "BaseMessage(content_blocks)": "langchain-core/messages/BaseMessage",
            "content_blocks": "langchain-core/messages/BaseMessage",
            "ContentBlock": "langchain/messages/ContentBlock",
            "TextContentBlock": "langchain/messages/TextContentBlock",
            "ReasoningContentBlock": "langchain/messages/ReasoningContentBlock",
            "NonStandardContentBlock": "langchain/messages/NonStandardContentBlock",
            "ImageContentBlock": "langchain/messages/ImageContentBlock",
            "VideoContentBlock": "langchain/messages/VideoContentBlock",
            "AudioContentBlock": "langchain/messages/AudioContentBlock",
            "PlainTextContentBlock": "langchain/messages/PlainTextContentBlock",
            "FileContentBlock": "langchain/messages/FileContentBlock",
            "ToolCall": "langchain/messages/ToolCall",
            "ToolCallChunk": "langchain/messages/ToolCallChunk",
            "ServerToolCall": "langchain/messages/ServerToolCall",
            "ServerToolCallChunk": "langchain/messages/ServerToolCallChunk",
            "ServerToolResult": "langchain/messages/ServerToolResult",
            # Integrations
            # langchain-openai
            "langchain-openai": "langchain-openai",
            "BaseChatOpenAI": "langchain-openai/base-chat-openai",
            "ChatOpenAI": "langchain-openai/chat-openai",
            "AzureChatOpenAI": "langchain-openai/azure-chat-openai",
            "OpenAI": "langchain-openai/openai",
            "AzureOpenAI": "langchain-openai/azure-openai",
            "OpenAIEmbeddings": "langchain-openai/openai-embeddings",
            "AzureOpenAIEmbeddings": "langchain-openai/azure-openai-embeddings",
            # langchain-anthropic
            "langchain-anthropic": "langchain-anthropic",
            "ChatAnthropic": "langchain-anthropic/chat-anthropic",
            "ChatAnthropic.bind_tools": "langchain-anthropic/chat-anthropic",
            "ChatAnthropic.get_num_tokens_from_messages": "langchain-anthropic/chat-anthropic",
            "AnthropicLLM": "langchain-anthropic/anthropic-llm",
            "AnthropicPromptCachingMiddleware": "langchain-anthropic/middleware",
            # langchain-google
            "langchain-google": "langchain-google-genai",
            "langchain-google-genai": "langchain-google-genai",
            "ChatGoogleGenerativeAI": "langchain-google-genai/chat-google-generative-ai",
            "langchain-google-vertexai": "langchain-google-vertexai",
            "ChatVertexAI": "langchain-google-vertexai/ChatVertexAI",
            "langchain-google-community": "langchain-google-community",
            # langchain-ollama
            "langchain-ollama": "langchain-ollama",
            "ChatOllama": "langchain-ollama/ChatOllama",
            # langchain-xai
            "langchain-xai": "langchain-xai",
            "ChatXAI": "langchain-xai/ChatXAI",
            # langchain-groq
            "langchain-groq": "langchain-groq",
            "ChatGroq": "langchain-groq/ChatGroq",
            # langchain-deepseek
            "langchain-deepseek": "langchain-deepseek",
            "ChatDeepSeek": "langchain-deepseek/ChatDeepSeek",
            # langchain-parallel
            "langchain-parallel": "langchain-parallel",
            "ChatParallelWeb": "langchain-parallel/ChatParallelWeb",
            "ParallelWebSearchTool": "langchain-parallel/ParallelWebSearchTool",
            "ParallelExtractTool": "langchain-parallel/ParallelExtractTool",
            # langchain-amazon-nova
            "langchain-amazon-nova": "langchain-amazon-nova",
            "ChatAmazonNova": "langchain-amazon-nova/ChatAmazonNova",
            "langchain_amazon_nova": "langchain-amazon-nova",
            # Models
            "init_chat_model": "langchain/chat_models/init_chat_model",
            "init_chat_model(model)": "langchain/chat_models/init_chat_model",
            "BaseChatModel": "langchain-core/language_models/chat_models/BaseChatModel",
            "BaseChatModel.invoke": "langchain-core/language_models/chat_models/BaseChatModel",
            "BaseChatModel.stream": "langchain-core/language_models/chat_models/BaseChatModel",
            "BaseChatModel.astream_events": "langchain-core/language_models/chat_models/BaseChatModel",
            "BaseChatModel.batch": "langchain-core/language_models/chat_models/BaseChatModel",
            "BaseChatModel.batch_as_completed": "langchain-core/language_models/chat_models/BaseChatModel",
            "BaseChatModel.bind_tools": "langchain-core/language_models/chat_models/BaseChatModel",
            "BaseChatModel.configurable_fields": "langchain-core/language_models/chat_models/BaseChatModel",
            "BaseChatModel.with_structured_output": "langchain-core/language_models/chat_models/BaseChatModel",
            "BaseChatModel.with_structured_output(include_raw)": "langchain-core/language_models/chat_models/BaseChatModel",
            "BaseChatModel.with_retry": "langchain-core/language_models/chat_models/BaseChatModel",
            # Prompts
            "ChatPromptTemplate": "langchain-core/prompts/chat/ChatPromptTemplate",
            # Tools
            "@tool": "langchain/tools/tool",
            "BaseTool": "langchain/tools/BaseTool",
            "ToolRuntime": "langchain/tools/ToolRuntime",
            "convert_to_openai_tool": "langchain-core/utils/function_calling/convert_to_openai_tool",
            # Embeddings
            "init_embeddings": "langchain-core/embeddings/embeddings/Embeddings",
            "Embeddings": "langchain-core/embeddings/embeddings/Embeddings",
            # Documents
            "Document": "langchain-core/documents/base/Document",
            # Document loaders
            "BaseLoader": "langchain-core/document_loaders/BaseLoader",
            # Text splitters
            "CharacterTextSplitter": "langchain-text-splitters/CharacterTextSplitter",
            "RecursiveCharacterTextSplitter": "langchain-text-splitters/RecursiveCharacterTextSplitter",
            "TokenTextSplitter": "langchain-text-splitters/TokenTextSplitter",
            # Runnables
            "Runnable": "langchain-core/runnables/Runnable",
            "RunnableConfig": "langchain-core/runnables/RunnableConfig",
            "RunnableLambda": "langchain-core/runnables/base/RunnableLambda",
            "RunnableConfig(max_concurrency)": "langchain-core/runnables/RunnableConfig",
            # Retrievers
            "Retrievers": "langchain-core/retrievers/BaseRetriever",
            # VectorStores
            "VectorStore": "langchain-core/vectorstores/base/VectorStore",
            "VectorStore.max_marginal_relevance_search": "langchain-core/vectorstores/base/VectorStore",
            # Key-value stores
            "BaseStore": "langgraph/store/base/BaseStore",
            "BaseStore.put": "langgraph/store/base/BaseStore",
            # Callbacks
            "on_llm_new_token": "langchain-core/callbacks/base/AsyncCallbackHandler",
            # Rate limiters
            "InMemoryRateLimiter": "langchain-core/rate_limiters/InMemoryRateLimiter",
            # LangSmith SDK
            "langsmith": "langsmith",
            "langsmith-python": "langsmith",
            "langsmith-js": "https://reference.langchain.com/javascript/langsmith",
            "wrapGemini": "https://reference.langchain.com/javascript/langsmith/wrappers/gemini/wrapGemini",
            "Client": "langsmith/client/Client",
            "Client.evaluate": "langsmith/client/Client",
            "Client.aevaluate": "langsmith/client/Client",
            "Client.get_experiment_results": "langsmith/client/Client",
            "ExperimentResults": "langsmith/evaluation/_runner/ExperimentResults",
            "wrap_openai": "langsmith/wrappers/wrap_openai",
            "wrap_anthropic": "langsmith/wrappers/wrap_anthropic",
            "wrap_gemini": "langsmith/wrappers/wrap_gemini",
            "traceable": "langsmith/run_helpers/traceable",
            "@traceable": "langsmith/run_helpers/traceable",
            "tracing_context": "langsmith/run_helpers/tracing_context",
            "tracingEnabled": "https://reference.langchain.com/javascript/langsmith/run_trees/RunTree",
            "langsmith_extra": "langsmith/run_helpers/SupportsLangsmithExtra",
            "SupportsLangsmithExtra": "langsmith/run_helpers/SupportsLangsmithExtra",
            # LangGraph
            "RemoteGraph": "langsmith/remote-graph",
            "RemoteGraph.as_tool": "langsmith/remote-graph",
            "get_stream_writer": "langgraph/config/get_stream_writer",
            "StateGraph": "langgraph/graph/state/StateGraph",
            "StateGraph.compile": "langgraph/graph/state/StateGraph",
            "add_edge": "langgraph/graph/state/StateGraph",
            "add_conditional_edges": "langgraph/graph/state/StateGraph",
            "add_node": "langgraph/graph/state/StateGraph",
            "add_messages": "langgraph/graph/message/add_messages",
            "CompiledStateGraph": "langgraph/graph/state/CompiledStateGraph",
            "CompiledStateGraph.astream": "langgraph/graph/state/CompiledStateGraph",
            "CompiledStateGraph.invoke": "langgraph/graph/state/CompiledStateGraph",
            "CompiledStateGraph.stream": "langgraph/graph/state/CompiledStateGraph",
            "get_state_history": "langgraph/graph/state/CompiledStateGraph",
            "update_state": "langgraph/graph/state/CompiledStateGraph",
            "InjectedState": "langgraph.prebuilt/tool_node/InjectedState",
            "InjectedStore": "langgraph.prebuilt/tool_node/InjectedStore",
            "InjectedToolCallId": "langchain/tools/InjectedToolCallId",
            "get_runtime": "langgraph/runtime/get_runtime",
            "Command": "langgraph/types/Command",
            "CachePolicy": "langgraph/types/CachePolicy",
            "interrupt": "langgraph/types/interrupt",
            "ToolNode": "langgraph.prebuilt/tool_node/ToolNode",
            "tools_condition": "langgraph.prebuilt/tool_node/tools_condition",
            "AsyncPostgresSaver": "langgraph.checkpoint.postgres/aio/AsyncPostgresSaver",
            "AsyncSqliteSaver": "langgraph.checkpoint.sqlite/aio/AsyncSqliteSaver",
            "BaseCheckpointSaver": "langgraph.checkpoint/base/BaseCheckpointSaver",
            "BinaryOperatorAggregate": "langgraph/channels/BinaryOperatorAggregate",
            "CipherProtocol": "langgraph.checkpoint/serde/base/CipherProtocol",
            "EncryptedSerializer": "langgraph.checkpoint/serde/encrypted/EncryptedSerializer",
            "from_pycryptodome_aes": "langgraph.checkpoint/serde/encrypted/EncryptedSerializer",
            "InMemorySaver": "langgraph.checkpoint/memory/InMemorySaver",
            "SerializerProtocol": "langgraph.checkpoint/serde/base/SerializerProtocol",
            "SqliteSaver": "langgraph.checkpoint.sqlite/SqliteSaver",
            "JsonPlusSerializer": "langgraph.checkpoint/serde/jsonplus/JsonPlusSerializer",
            "PostgresSaver": "langgraph.checkpoint.postgres/PostgresSaver",
            "PostgresStore": "langgraph/store/postgres/PostgresStore",
            "create_react_agent": "langgraph.prebuilt/chat_agent_executor/create_react_agent",
            "LastValue": "langgraph/channels/LastValue",
            "START": "langgraph/constants/START",
            "Pregel": "langgraph/pregel",
            "Pregel.astream": "langgraph/pregel/Pregel",
            "Pregel.stream": "langgraph/pregel/Pregel",
            "Runtime": "langgraph/runtime/Runtime",
            "Send": "langgraph/types/Send",
            "Topic": "langgraph/channels/Topic",
            # LangSmith Deployment SDK
            # Main client
            "get_client": "langgraph-sdk/get_client",
            "get_sync_client": "langgraph-sdk/get_sync_client",
            "LangGraphClient": "langgraph-sdk/client/LangGraphClient",
            # HTTP clients
            "HttpClient": "langgraph-sdk/client/HttpClient",
            "SyncHttpClient": "langgraph-sdk/client/SyncHttpClient",
            # Resource clients - Async
            "AssistantsClient": "langgraph-sdk/client/AssistantsClient",
            "AssistantsClient.create": "langgraph-sdk/client/AssistantsClient",
            "AssistantsClient.update": "langgraph-sdk/client/AssistantsClient",
            "LangGraphSDK": "langgraph-sdk",
            "ThreadsClient": "langgraph-sdk/client/ThreadsClient",
            "ThreadsClient.create": "langgraph-sdk/client/ThreadsClient",
            "ThreadsClient.copy": "langgraph-sdk/client/ThreadsClient",
            "ThreadsClient.get": "langgraph-sdk/client/ThreadsClient",
            "ThreadsClient.get_state": "langgraph-sdk/client/ThreadsClient",
            "ThreadsClient.search": "langgraph-sdk/client/ThreadsClient",
            "ThreadsClient.get_history": "langgraph-sdk/client/ThreadsClient",
            "RunsClient": "langgraph-sdk/client/RunsClient",
            "RunsClient.stream": "langgraph-sdk/client/RunsClient",
            "CronClient": "langgraph-sdk/client/CronClient",
            "StoreClient": "langgraph-sdk/client/StoreClient",
            # Resource clients - Sync
            "SyncAssistantsClient": "langgraph-sdk/client/SyncAssistantsClient",
            "SyncThreadsClient": "langgraph-sdk/client/SyncThreadsClient",
            "SyncRunsClient": "langgraph-sdk/client/SyncRunsClient",
            "SyncCronClient": "langgraph-sdk/client/SyncCronClient",
            "SyncStoreClient": "langgraph-sdk/client/SyncStoreClient",
            # Client methods
            "client.runs.stream": "langgraph-sdk/client/RunsClient",
            "client.runs.wait": "langgraph-sdk/client/RunsClient",
            "client.threads.get_history": "langgraph-sdk/client/ThreadsClient",
            "client.threads.update_state": "langgraph-sdk/client/ThreadsClient",
            # Schema types - Enumerations
            "RunStatus": "langgraph-sdk/schema/RunStatus",
            "ThreadStatus": "langgraph-sdk/schema/ThreadStatus",
            "StreamMode": "langgraph-sdk/schema/StreamMode",
            "DisconnectMode": "langgraph-sdk/schema/DisconnectMode",
            "MultitaskStrategy": "langgraph-sdk/schema/MultitaskStrategy",
            "OnConflictBehavior": "langgraph-sdk/schema/OnConflictBehavior",
            # Schema types - Data models
            "Assistant": "langgraph-sdk/schema/Assistant",
            "AssistantVersion": "langgraph-sdk/schema/AssistantVersion",
            "Thread": "langgraph-sdk/schema/Thread",
            "Run": "langgraph-sdk/schema/Run",
            "Cron": "langgraph-sdk/schema/Cron",
            "Config": "langgraph-sdk/schema/Config",
            "Checkpoint": "langgraph-sdk/schema/Checkpoint",
            "GraphSchema": "langgraph-sdk/schema/GraphSchema",
            "Item": "langgraph-sdk/schema/Item",
            "SearchItem": "langgraph-sdk/schema/SearchItem",
            "ThreadState": "langgraph-sdk/schema/ThreadState",
            # Auth types
            "Auth": "langgraph-sdk/auth/Auth",
            "Auth.authenticate": "langgraph-sdk/auth/Auth",
            "Auth.on": "langgraph-sdk/auth/Auth",
            "AuthContext": "langgraph-sdk/auth/types/AuthContext",
            "BaseUser": "langgraph-sdk/auth/types/BaseUser",
            "StudioUser": "langgraph-sdk/auth/types/StudioUser",
            "MinimalUserDict": "langgraph-sdk/auth/types/MinimalUserDict",
            "HTTPException": "langgraph-sdk/auth/exceptions/HTTPException",
            # Auth types - Threads
            "ThreadsCreate": "langgraph-sdk/auth/types/ThreadsCreate",
            "ThreadsRead": "langgraph-sdk/auth/types/ThreadsRead",
            "ThreadsUpdate": "langgraph-sdk/auth/types/ThreadsUpdate",
            "ThreadsDelete": "langgraph-sdk/auth/types/ThreadsDelete",
            "ThreadsSearch": "langgraph-sdk/auth/types/ThreadsSearch",
            # Auth types - Assistants
            "AssistantsCreate": "langgraph-sdk/auth/types/AssistantsCreate",
            "AssistantsRead": "langgraph-sdk/auth/types/AssistantsRead",
            "AssistantsUpdate": "langgraph-sdk/auth/types/AssistantsUpdate",
            "AssistantsDelete": "langgraph-sdk/auth/types/AssistantsDelete",
            "AssistantsSearch": "langgraph-sdk/auth/types/AssistantsSearch",
            # Auth types - Runs
            "RunsCreate": "langgraph-sdk/auth/types/RunsCreate",
            # Auth types - Crons
            "CronsCreate": "langgraph-sdk/auth/types/CronsCreate",
            "CronsRead": "langgraph-sdk/auth/types/CronsRead",
            "CronsUpdate": "langgraph-sdk/auth/types/CronsUpdate",
            "CronsDelete": "langgraph-sdk/auth/types/CronsDelete",
            "CronsSearch": "langgraph-sdk/auth/types/CronsSearch",
            # Schema create types
            "RunCreate": "langgraph-sdk/schema/RunCreate",
            "RunCreateMetadata": "langgraph-sdk/schema/RunCreateMetadata",
            # Functional API
            "task": "langgraph/func/task",
            "@task": "langgraph/func/task",
            "@entrypoint": "langgraph/func/entrypoint",
            "entrypoint.final": "langgraph/func/entrypoint",
            # Configuration
            "langgraph.json": "cloud/reference/cli/#configuration-file",
            # MCP stuff
            "MultiServerMCPClient": "langchain-mcp-adapters/client/MultiServerMCPClient",
            "load_mcp_tools": "langchain-mcp-adapters/tools/load_mcp_tools",
            "load_mcp_prompt": "langchain-mcp-adapters/prompts/load_mcp_prompt",
            "load_mcp_resources": "langchain-mcp-adapters/resources/load_mcp_resources",
            "MCPToolArtifact": "langchain-mcp-adapters/tools/MCPToolArtifact",
            "ToolCallInterceptor": "langchain-mcp-adapters/interceptors/ToolCallInterceptor",
            "CallbackContext": "langchain-mcp-adapters/callbacks/CallbackContext",
            "Callbacks": "langchain-mcp-adapters/callbacks/Callbacks",
            "Connection": "langchain-mcp-adapters/sessions/Connection",
            "McpHttpClientFactory": "langchain-mcp-adapters/sessions/McpHttpClientFactory",
            "StdioConnection": "langchain-mcp-adapters/sessions/StdioConnection",
            "StreamableHttpConnection": "langchain-mcp-adapters/sessions/StreamableHttpConnection",
            "WebsocketConnection": "langchain-mcp-adapters/sessions/WebsocketConnection",
            # LangSmith SDK - Vitest/Jest references (JS-only, but added here for cross-scope compatibility)
            "langsmith.vitest": "https://reference.langchain.com/javascript/langsmith/vitest",
            "langsmith/vitest": "https://reference.langchain.com/javascript/langsmith/vitest",
            "langsmith.jest": "https://reference.langchain.com/javascript/langsmith/jest",
            "langsmith/jest": "https://reference.langchain.com/javascript/langsmith/jest",
            "ls.describe": "https://reference.langchain.com/javascript/langsmith/vitest/describe",
            "ls.test": "https://reference.langchain.com/javascript/langsmith/vitest/test",
            "ls.test.each": "https://reference.langchain.com/javascript/langsmith/vitest/test",
            "ls.wrapEvaluator": "https://reference.langchain.com/javascript/langsmith/vitest/wrapEvaluator",
            "ls.logOutputs": "https://reference.langchain.com/javascript/langsmith/vitest/logOutputs",
            "ls.logFeedback": "https://reference.langchain.com/javascript/langsmith/vitest/logFeedback",
            "Client.listExamples": "https://reference.langchain.com/javascript/langsmith/client/Client",
            "Example": "https://reference.langchain.com/javascript/langsmith/Example",
        },
    },
    {
        "host": "https://reference.langchain.com/javascript/",
        "scope": "js",
        "links": {
            # @langchain/core references
            "AIMessage": "langchain-core/messages/AIMessage",
            "AIMessageChunk": "langchain-core/messages/AIMessageChunk",
            "BaseMessage": "langchain-core/messages/BaseMessage",
            "HumanMessage": "langchain-core/messages/HumanMessage",
            "SystemMessage": "langchain-core/messages/SystemMessage",
            "SystemMessage.concat": "langchain-core/messages/SystemMessage",
            "ToolMessage": "langchain-core/messages/ToolMessage",
            "ToolCallChunk": "langchain-core/messages/ToolCallChunk",
            "BaseChatModel": "langchain-core/language_models/chat_models/BaseChatModel",
            "BaseChatModel.invoke": "langchain-core/language_models/chat_models/BaseChatModel",
            "BaseChatModel.stream": "langchain-core/language_models/chat_models/BaseChatModel",
            "BaseChatModel.streamEvents": "langchain-core/language_models/chat_models/BaseChatModel",
            "BaseChatModel.batch": "langchain-core/language_models/chat_models/BaseChatModel",
            "BaseChatModel.bindTools": "langchain-core/language_models/chat_models/BaseChatModel",
            "BaseChatModel.with_structured_output": "langchain-core/language_models/chat_models/BaseChatModel",
            "BaseChatModel.with_structured_output(include_raw)": "langchain-core/language_models/chat_models/BaseChatModel",
            "BaseTool": "langchain-core/tools/StructuredTool",
            "ContentBlock": "langchain-core/messages/MessageContent",
            "ChatOpenAI": "langchain-openai/ChatOpenAI",
            "AzureChatOpenAI": "langchain-openai/AzureChatOpenAI",
            "Document": "langchain-core/documents/Document",
            "Embeddings": "langchain-core/embeddings/Embeddings",
            "initChatModel": "langchain/chat_models/universal/initChatModel",
            "Runnable": "langchain-core/runnables/Runnable",
            "RunnableConfig": "langchain-core/runnables/RunnableConfig",
            "Retrievers": "langchain-core/retrievers/BaseRetriever",
            "VectorStore": "langchain-core/vectorstores/VectorStore",
            "VectorStore.maxMarginalRelevanceSearch": "langchain-core/vectorstores/VectorStore",
            "tool": "langchain-core/tools/tool",
            "UsageMetadata": "langchain-core/messages/UsageMetadata",
            "BaseLoader": "langchain-core/document_loaders/base/BaseDocumentLoader",
            "getContextVariable": "langchain-core/context/getContextVariable",
            "astream_events": "langchain-core/runnables/Runnable",
            "on_llm_new_token": "langchain-core/callbacks/base/BaseCallbackHandlerMethods",
            "langchain.messages": "langchain-core/messages",
            "BaseMessage(content)": "langchain-core/messages/BaseMessage",
            # Text splitters
            "RecursiveCharacterTextSplitter": "langchain-textsplitters/RecursiveCharacterTextSplitter",
            "TokenTextSplitter": "langchain-textsplitters/TokenTextSplitter",
            # LangSmith SDK
            "langsmith": "langsmith",
            "langsmith-js": "langsmith",
            "langsmith-python": "https://reference.langchain.com/python/langsmith",
            "tracingEnabled": "langsmith/run_trees/RunTree",
            "wrapGemini": "langsmith/wrappers/gemini/wrapGemini",
            # LangGraph SDK references
            "Auth": "langchain-langgraph-sdk/auth/Auth",
            "client.runs.stream": "langchain-langgraph-sdk/client/RunsClient",
            "client.runs.wait": "langchain-langgraph-sdk/client/RunsClient",
            "client.threads.get_history": "langchain-langgraph-sdk/client/ThreadsClient",
            "client.threads.update_state": "langchain-langgraph-sdk/client/ThreadsClient",
            # LangGraph checkpoint references
            "BaseCheckpointSaver": "langchain-langgraph-checkpoint/BaseCheckpointSaver",
            "BaseStore": "langchain-langgraph-checkpoint/BaseStore",
            "BaseStore.put": "langchain-langgraph-checkpoint/BaseStore",
            "InMemorySaver": "langchain-langgraph-checkpoint/MemorySaver",
            "MemorySaver": "langchain-langgraph-checkpoint/MemorySaver",
            "AsyncPostgresSaver": "langchain-langgraph-checkpoint-postgres/AsyncPostgresSaver",
            "PostgresSaver": "langchain-langgraph-checkpoint-postgres/PostgresSaver",
            "protocol": "langchain-langgraph-checkpoint/SerializerProtocol",
            "SerializerProtocol": "langchain-langgraph-checkpoint/SerializerProtocol",
            "SqliteSaver": "langchain-langgraph-checkpoint-sqlite/SqliteSaver",
            # LangGraph core references
            "StateGraph": "langchain-langgraph/StateGraph",
            "StateGraph.compile": "langchain-langgraph/StateGraph",
            "add_conditional_edges": "langchain-langgraph/StateGraph",
            "addConditionalEdges": "langchain-langgraph/StateGraph",
            "add_edge": "langchain-langgraph/StateGraph",
            "addEdge": "langchain-langgraph/StateGraph",
            "add_node": "langchain-langgraph/StateGraph",
            "add_messages": "langchain-langgraph/messagesStateReducer",
            "LastValue": "langchain-langgraph/channels/LastValue",
            "Topic": "langchain-langgraph/channels/Topic",
            "BinaryOperatorAggregate": "langchain-langgraph/BinaryOperatorAggregate",
            "Command": "langchain-langgraph/Command",
            "CompiledStateGraph": "langchain-langgraph/CompiledStateGraph",
            "createAgent": "langchain/createAgent",
            "createMiddleware": "langchain/createMiddleware",
            "createReactAgent": "langchain-langgraph/prebuilt/createReactAgent",
            "createSupervisor": "langchain-langgraph-supervisor/createSupervisor",
            "entrypoint": "langchain-langgraph/entrypoint",
            "entrypoint.final": "langchain-langgraph/entrypoint",
            "get_state_history": "langchain-langgraph/pregel/Pregel",
            "getStateHistory": "langchain-langgraph/pregel/Pregel",
            "HumanInterrupt": "langchain-langgraph/prebuilt/HumanInterrupt",
            "interrupt": "langchain-langgraph/interrupt",
            "CompiledStateGraph.invoke": "langchain-langgraph/CompiledStateGraph",
            "langgraph.json": "cloud/reference/cli/#configuration-file",
            "messagesStateReducer": "langchain-langgraph/messagesStateReducer",
            "Pregel": "langchain-langgraph/pregel/Pregel",
            "Pregel.stream": "langchain-langgraph/pregel/Pregel",
            "Send": "langchain-langgraph/Send",
            "START": "langchain-langgraph/START",
            "CompiledStateGraph.stream": "langchain-langgraph/CompiledStateGraph",
            "task": "langchain-langgraph/task",
            "update_state": "langchain-langgraph/pregel/Pregel",
            "updateState": "langchain-langgraph/pregel/Pregel",
            "Runtime": "langchain-langgraph/Runtime",
            "ToolNode": "langchain-langgraph/prebuilt/ToolNode",
            # LangSmith Deployment SDK - JS
            "LangGraphSDK": "langchain-langgraph-sdk",
            "ThreadsClient": "langchain-langgraph-sdk/client/ThreadsClient",
            "ThreadsClient.create": "langchain-langgraph-sdk/client/ThreadsClient",
            "ThreadsClient.copy": "langchain-langgraph-sdk/client/ThreadsClient",
            "ThreadsClient.get": "langchain-langgraph-sdk/client/ThreadsClient",
            "ThreadsClient.get_state": "langchain-langgraph-sdk/client/ThreadsClient",
            "ThreadsClient.search": "langchain-langgraph-sdk/client/ThreadsClient",
            "ThreadsClient.get_history": "langchain-langgraph-sdk/client/ThreadsClient",
            "ThreadsClient.getHistory": "langchain-langgraph-sdk/client/ThreadsClient",
            "AssistantsClient": "langchain-langgraph-sdk/client/AssistantsClient",
            "AssistantsClient.create": "langchain-langgraph-sdk/client/AssistantsClient",
            "AssistantsClient.update": "langchain-langgraph-sdk/client/AssistantsClient",
            "AssistantsClient.search": "langchain-langgraph-sdk/client/AssistantsClient",
            "RunsClient": "langchain-langgraph-sdk/client/RunsClient",
            "RunsClient.stream": "langchain-langgraph-sdk/client/RunsClient",
            "ClearToolUsesEdit": "langchain/ClearToolUsesEdit",
            "ContextEdit": "langchain/ContextEdit",
            "toolRetryMiddleware": "langchain/toolRetryMiddleware",
            "modelRetryMiddleware": "langchain/modelRetryMiddleware",
            "systemPrompt": "langchain/CreateAgentParams",
            "openAIModerationMiddleware": "langchain-openai/middleware/OpenAIModerationMiddleware",
            # LangSmith SDK - Vitest references
            "langsmith.vitest": "langsmith/vitest",
            "langsmith/vitest": "langsmith/vitest",
            "ls.describe": "langsmith/vitest/describe",
            "ls.test": "langsmith/vitest/test",
            "ls.test.each": "langsmith/vitest/test",
            "ls.wrapEvaluator": "langsmith/vitest/wrapEvaluator",
            "ls.logOutputs": "langsmith/vitest/logOutputs",
            "ls.logFeedback": "langsmith/vitest/logFeedback",
            "wrapVitest": "langsmith/vitest/wrapVitest",
            # LangSmith SDK - Jest references
            "langsmith.jest": "langsmith/jest",
            "langsmith/jest": "langsmith/jest",
            "wrapJest": "langsmith/jest/wrapJest",
            # LangSmith SDK - Core client references
            "Client.listExamples": "langsmith/client/Client",
            "Example": "langsmith/Example",
        },
    },
    {
        # LangSmith Deployment Agent Server API - Python scope
        "host": "https://langchain-ai.github.io/langgraph/cloud/reference/api/",
        "scope": "python",
        "links": {
            "AssistantsAPI": "api_ref.html#tag/assistants",
            "ThreadsAPI": "api_ref.html#tag/threads",
            "ThreadsAPI.create": "api_ref.html#tag/threads/post/threads",
            "ThreadsAPI.copy": "api_ref.html#tag/threads/post/threads/{thread_id}/copy",
            "ThreadsAPI.get": "api_ref.html#tag/threads/get/threads/{thread_id}",
            "ThreadsAPI.get_state": "api_ref.html#tag/threads/get/threads/{thread_id}/state",
            "ThreadsAPI.search": "api_ref.html#tag/threads/post/threads/search",
            "ThreadsAPI.get_history": "api_ref.html#tag/threads/post/threads/{thread_id}/history",
        },
    },
    {
        # LangSmith Deployment Agent Server API - JS scope
        "host": "https://langchain-ai.github.io/langgraph/cloud/reference/api/",
        "scope": "js",
        "links": {
            "AssistantsAPI": "api_ref.html#tag/assistants",
            "ThreadsAPI": "api_ref.html#tag/threads",
            "ThreadsAPI.create": "api_ref.html#tag/threads/post/threads",
            "ThreadsAPI.copy": "api_ref.html#tag/threads/post/threads/{thread_id}/copy",
            "ThreadsAPI.get": "api_ref.html#tag/threads/get/threads/{thread_id}",
            "ThreadsAPI.get_state": "api_ref.html#tag/threads/get/threads/{thread_id}/state",
            "ThreadsAPI.search": "api_ref.html#tag/threads/post/threads/search",
            "ThreadsAPI.get_history": "api_ref.html#tag/threads/post/threads/{thread_id}/history",
        },
    },
]


def _enumerate_links(scope: str) -> dict[str, str]:
    result = {}
    for link_map in LINK_MAPS:
        if link_map["scope"] == scope:
            links = link_map["links"]
            for key, value in links.items():
                if not value.startswith("http"):
                    result[key] = f"{link_map['host']}{value}"
                else:
                    result[key] = value
    return result


# Global scope is assembled from the Python and JS mappings
# Combined mapping by scope
SCOPE_LINK_MAPS = {
    "python": _enumerate_links("python"),
    "js": _enumerate_links("js"),
}
